package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"log/slog"
	"strconv"

	"github.com/trust-me-im-an-engineer/mini-reddit/graph/model"
	"github.com/trust-me-im-an-engineer/mini-reddit/internal/converter"
	"github.com/trust-me-im-an-engineer/mini-reddit/internal/errs"
	"github.com/trust-me-im-an-engineer/mini-reddit/internal/validator"
)

// Children is the resolver for the children field.
func (r *commentResolver) Children(ctx context.Context, obj *model.Comment, sort model.SortOrder, limit int32, cursor *string, depth int32) (*model.CommentConnection, error) {
	panic(fmt.Errorf("not implemented: Children - children"))
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	if err := validator.ValidateCreatePostInput(input); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.CreatePostInput_ModelToDomain(&input)

	domainPost, err := r.postService.CreatePost(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("post service failed to create post", "error", err)
		return nil, errs.InternalServer
	}

	return converter.Post_DomainToModel(domainPost), nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (*model.Post, error) {
	if err := validator.ValidateUpdatePostInput(input); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.UpdatePost_ModelToDomain(&input)

	domainPost, err := r.postService.UpdatePost(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("post service failed to update post", "error", err)
		return nil, errs.InternalServer
	}

	return converter.Post_DomainToModel(domainPost), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	domainID, err := strconv.Atoi(id)
	if err != nil {
		return false, errs.InvalidInputWrap(errs.InvalidID)
	}

	err = r.postService.DeletePost(ctx, domainID)
	if err := errs.Exposable(err); err != nil {
		return false, err
	}
	if err != nil {
		slog.Error("post service failed to delete post", "id", domainID, "error", err)
		return false, errs.InternalServer
	}

	return true, nil
}

// SetCommentsRestricted is the resolver for the setCommentsRestricted field.
func (r *mutationResolver) SetCommentsRestricted(ctx context.Context, postID string, restricted bool) (*model.Post, error) {
	domainID, err := strconv.Atoi(postID)
	if err != nil {
		return nil, errs.InvalidInputWrap(fmt.Errorf("invalid post id: %w", err))
	}

	domainPost, err := r.postService.SetCommentsRestricted(ctx, domainID, restricted)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("post service failed to set comments restricted", "id", domainID, "error", err)
		return nil, errs.InternalServer
	}

	return converter.Post_DomainToModel(domainPost), nil
}

// VotePost is the resolver for the votePost field.
func (r *mutationResolver) VotePost(ctx context.Context, input model.VoteInput) (*model.Post, error) {
	if err := validator.ValidateVoteInput(input); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.ModelVoteInputToDomainPostVote(&input)

	domainPost, err := r.postService.VotePost(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("post service failed to downvote post", "error", err)
		return nil, errs.InternalServer
	}

	return converter.Post_DomainToModel(domainPost), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	if err := validator.ValidateCreateCommentInput(input); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.CreateCommentInput_ModelToDomain(&input)

	domainComment, err := r.commentService.CreateComment(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("comment service failed to create comment", "error", err)
		return nil, errs.InternalServer
	}

	modelComment := converter.Comment_DomainToModel(domainComment)

	r.subscriptionService.PublishComment(domainInput.PostID, modelComment)

	return modelComment, nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input model.UpdateCommentInput) (*model.Comment, error) {
	if err := validator.ValidateUpdateCommentInput(input); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.UpdateCommentInput_ModelToDomain(&input)

	domainComment, err := r.commentService.UpdateComment(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("comment service failed to update comment", "error", err)
		return nil, errs.InternalServer
	}

	return converter.Comment_DomainToModel(domainComment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	domainID, err := strconv.Atoi(id)
	if err != nil {
		return false, errs.InvalidInputWrap(errs.InvalidID)
	}

	err = r.commentService.DeleteComment(ctx, domainID)
	if err := errs.Exposable(err); err != nil {
		return false, err
	}
	if err != nil {
		slog.Error("comment service failed to delete comment", "id", domainID, "error", err)
		return false, errs.InternalServer
	}

	return true, nil
}

// VoteComment is the resolver for the voteComment field.
func (r *mutationResolver) VoteComment(ctx context.Context, input model.VoteInput) (*model.Comment, error) {
	if err := validator.ValidateVoteInput(input); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.ModelVoteInputToDomainCommentVote(&input)

	domainComment, err := r.commentService.VoteComment(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("comment service failed to downvote comment", "error", err)
		return nil, errs.InternalServer
	}

	return converter.Comment_DomainToModel(domainComment), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, sort model.SortOrder, limit int32, cursor *string, depth int32) (*model.CommentConnection, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	domainID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errs.InvalidInputWrap(errs.InvalidID)
	}

	internalPost, err := r.postService.GetPost(ctx, domainID)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("post service failed to get post", "id", domainID, "error", err)
		return nil, errs.InternalServer
	}

	return converter.Post_DomainToModel(internalPost), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, sort model.SortOrder, limit int32, cursor *string) (*model.PostConnection, error) {
	if err := validator.ValidatePostsInput(sort, limit, cursor); err != nil {
		return nil, errs.InvalidInputWrap(err)
	}

	domainInput := converter.PostsInput(sort, limit, cursor)

	domainPostConnection, err := r.postService.GetPosts(ctx, domainInput)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("post service failed to get posts", "sort", domainInput.Sort, "limit", domainInput.Limit, "cursor", cursor, "error", err)
		return nil, errs.InternalServer
	}

	return converter.PostConnection_DomainToModel(domainPostConnection), nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	domainID, err := strconv.Atoi(id)
	if err != nil {
		return nil, errs.InvalidInputWrap(errs.InvalidID)
	}

	internalComment, err := r.commentService.GetComment(ctx, domainID)
	if err := errs.Exposable(err); err != nil {
		return nil, err
	}
	if err != nil {
		slog.Error("comment service failed to get comment", "id", domainID, "error", err)
		return nil, errs.InternalServer
	}

	return converter.Comment_DomainToModel(internalComment), nil
}

// NewComment is the resolver for the newComment field.
func (r *subscriptionResolver) NewComment(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	domainPostID, err := strconv.Atoi(postID)
	if err != nil {
		return nil, errs.InvalidInputWrap(errs.InvalidID)
	}

	ch := make(chan *model.Comment, 10)

	r.subscriptionService.SubscribeToPost(domainPostID, ch)
	go func() {
		<-ctx.Done()
		r.subscriptionService.UnsubscribeFromPost(domainPostID, ch)
		slog.Debug("subscription closed", "postID", domainPostID)
	}()

	return ch, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
